// flow-typed signature: 156b59757463abe7c357b523a6531482
// flow-typed version: <<STUB>>/kefir.combines_v^3.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kefir.combines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kefir.combines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kefir.combines/lib/kefir.combines' {
  declare module.exports: any;
}

declare module 'kefir.combines/src/kefir.combines' {
  declare module.exports: any;
}

declare module 'kefir.combines/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kefir.combines/lib/kefir.combines.js' {
  declare module.exports: $Exports<'kefir.combines/lib/kefir.combines'>;
}
declare module 'kefir.combines/src/kefir.combines.js' {
  declare module.exports: $Exports<'kefir.combines/src/kefir.combines'>;
}
declare module 'kefir.combines/test/tests.js' {
  declare module.exports: $Exports<'kefir.combines/test/tests'>;
}
