// flow-typed signature: 3a1eb61104b1416e71a583d7cc9ba5ba
// flow-typed version: <<STUB>>/material-colors_v^1.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-colors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-colors/dist/colors.es2015' {
  declare module.exports: any;
}

declare module 'material-colors/dist/colors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-colors/dist/colors.es2015.js' {
  declare module.exports: $Exports<'material-colors/dist/colors.es2015'>;
}
declare module 'material-colors/dist/colors.js' {
  declare module.exports: $Exports<'material-colors/dist/colors'>;
}
