// flow-typed signature: 4b5b17294aef496343bd05a345a0382d
// flow-typed version: <<STUB>>/partial.lenses_v^7.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'partial.lenses'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'partial.lenses' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'partial.lenses/bench/bench' {
  declare module.exports: any;
}

declare module 'partial.lenses/lib/partial.lenses' {
  declare module.exports: any;
}

declare module 'partial.lenses/src/partial.lenses' {
  declare module.exports: any;
}

declare module 'partial.lenses/test/bst' {
  declare module.exports: any;
}

declare module 'partial.lenses/test/core' {
  declare module.exports: any;
}

declare module 'partial.lenses/test/tests' {
  declare module.exports: any;
}

declare module 'partial.lenses/test/type' {
  declare module.exports: any;
}

declare module 'partial.lenses/test/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'partial.lenses/bench/bench.js' {
  declare module.exports: $Exports<'partial.lenses/bench/bench'>;
}
declare module 'partial.lenses/lib/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/lib/partial.lenses'>;
}
declare module 'partial.lenses/src/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/src/partial.lenses'>;
}
declare module 'partial.lenses/test/bst.js' {
  declare module.exports: $Exports<'partial.lenses/test/bst'>;
}
declare module 'partial.lenses/test/core.js' {
  declare module.exports: $Exports<'partial.lenses/test/core'>;
}
declare module 'partial.lenses/test/tests.js' {
  declare module.exports: $Exports<'partial.lenses/test/tests'>;
}
declare module 'partial.lenses/test/type.js' {
  declare module.exports: $Exports<'partial.lenses/test/type'>;
}
declare module 'partial.lenses/test/types.js' {
  declare module.exports: $Exports<'partial.lenses/test/types'>;
}
